"""Train the landslide hazard model.

    python ml/train_model.py                    # 24 000 rows, auto backend
    python ml/train_model.py --rows 60000        # regenerate a larger set
    python ml/train_model.py --backend numpy     # force the dependency-free one

What it produces
----------------
`ml/model.pkl` holds a bagged ensemble plus everything needed to serve and
audit it: the feature contract, the chosen backend, evaluation metrics, a
calibration table, and the training-data summary. `ml/model_card.json` is the
same metadata in readable form for the docs and the /api/model endpoint.

Backend selection is deliberate, not accidental
-----------------------------------------------
XGBoost is preferred, scikit-learn is next, and `ml/fallback_gbm.NumpyGBM`
(same Newton boosting, NumPy only) is last. All three are trained and scored by
identical code, so a laptop where `pip install xgboost` fails still gets a real
gradient-boosted model with real metrics rather than a stub - and the report
says which backend produced it.

Honest labelling
----------------
The training rows are SYNTHETIC, generated by the documented physical model in
`ml/physics.py`. Metrics below describe how well the model recovers that
process from noisy samples of it. They are not evidence of real-world landslide
forecast skill, and the model card records this in `data_provenance`.
"""
from __future__ import annotations

import argparse
import json
import pickle
import sys
import time
from pathlib import Path
from typing import Any, Callable, Sequence

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from ml import MODEL_NAME, MODEL_VERSION
from ml.fallback_gbm import NumpyGBM
from ml.features import (
    FACTOR_GROUPS,
    FEATURE_ORDER,
    FEATURE_SCHEMA_VERSION,
    risk_level,
)
from ml.preprocess import (
    GROUP_COLUMN,
    frame_to_matrix,
    group_split,
    labels,
    summarise,
)

HERE = Path(__file__).resolve().parent
DEFAULT_DATA = HERE / "data" / "training_data.csv"
DEFAULT_MODEL = HERE / "model.pkl"
DEFAULT_CARD = HERE / "model_card.json"
BAND_ORDER = ["VERY LOW", "LOW", "MODERATE", "HIGH", "CRITICAL"]

# Shared across backends so the comparison is like-for-like. Depth is modest
# and min_child_weight high because grouped validation showed deeper trees
# memorising individual regions without improving unseen-region AUC.
HYPERPARAMS = {
    "n_estimators": 300,
    "learning_rate": 0.09,
    "max_depth": 4,
    "min_child_weight": 12.0,
    "reg_lambda": 2.0,
    "subsample": 0.85,
    "colsample_bytree": 0.9,
}


def _xgboost_factory() -> Callable[[int], Any] | None:
    try:
        from xgboost import XGBClassifier
    except Exception:
        return None

    def make(seed: int) -> Any:
        return XGBClassifier(
            n_estimators=HYPERPARAMS["n_estimators"],
            learning_rate=HYPERPARAMS["learning_rate"],
            max_depth=HYPERPARAMS["max_depth"],
            min_child_weight=HYPERPARAMS["min_child_weight"],
            reg_lambda=HYPERPARAMS["reg_lambda"],
            subsample=HYPERPARAMS["subsample"],
            colsample_bytree=HYPERPARAMS["colsample_bytree"],
            objective="binary:logistic",
            eval_metric="logloss",
            tree_method="hist",
            random_state=seed,
            n_jobs=0,
            verbosity=0,
        )

    return make


def _sklearn_factory() -> Callable[[int], Any] | None:
    try:
        from sklearn.ensemble import HistGradientBoostingClassifier
    except Exception:
        return None

    def make(seed: int) -> Any:
        return HistGradientBoostingClassifier(
            max_iter=HYPERPARAMS["n_estimators"],
            learning_rate=HYPERPARAMS["learning_rate"],
            max_depth=HYPERPARAMS["max_depth"] + 1,
            min_samples_leaf=40,
            l2_regularization=HYPERPARAMS["reg_lambda"],
            max_bins=64,
            early_stopping=False,
            random_state=seed,
        )

    return make


def _numpy_factory() -> Callable[[int], Any]:
    def make(seed: int) -> Any:
        return NumpyGBM(
            n_estimators=HYPERPARAMS["n_estimators"],
            learning_rate=HYPERPARAMS["learning_rate"],
            max_depth=HYPERPARAMS["max_depth"],
            min_child_weight=HYPERPARAMS["min_child_weight"],
            reg_lambda=HYPERPARAMS["reg_lambda"],
            subsample=HYPERPARAMS["subsample"],
            colsample_bytree=HYPERPARAMS["colsample_bytree"],
            random_state=seed,
        )

    return make


def resolve_backend(preferred: str = "auto") -> tuple[str, Callable[[int], Any]]:
    """Pick the best available backend, honouring an explicit request."""
    options: list[tuple[str, Callable[[], Callable[[int], Any] | None]]] = [
        ("xgboost", _xgboost_factory),
        ("sklearn", _sklearn_factory),
        ("numpy", lambda: _numpy_factory()),
    ]
    if preferred != "auto":
        for name, loader in options:
            if name == preferred:
                factory = loader()
                if factory is None:
                    raise SystemExit(f"backend '{preferred}' requested but not installed")
                return name, factory
        raise SystemExit(f"unknown backend '{preferred}'")
    for name, loader in options:
        factory = loader()
        if factory is not None:
            return name, factory
    raise SystemExit("no usable backend")  # pragma: no cover - numpy is required


# --------------------------------------------------------------------- metrics
# Written out in NumPy rather than imported from scikit-learn, because the whole
# point of the fallback backend is that the pipeline still runs and still
# reports honest numbers when scikit-learn is not installed.

def roc_auc(y: np.ndarray, p: np.ndarray) -> float:
    """Rank-based AUC (Mann-Whitney U), tie-corrected via average ranks."""
    y = np.asarray(y).ravel()
    positives = int(y.sum())
    negatives = y.size - positives
    if positives == 0 or negatives == 0:
        return float("nan")
    order = np.argsort(p, kind="mergesort")
    ranks = np.empty(p.size, dtype=float)
    ranks[order] = np.arange(1, p.size + 1, dtype=float)
    sorted_p = p[order]
    start = 0
    while start < sorted_p.size:
        stop = start + 1
        while stop < sorted_p.size and sorted_p[stop] == sorted_p[start]:
            stop += 1
        if stop - start > 1:
            ranks[order[start:stop]] = ranks[order[start:stop]].mean()
        start = stop
    return float((ranks[y == 1].sum() - positives * (positives + 1) / 2.0) / (negatives * positives))


def average_precision(y: np.ndarray, p: np.ndarray) -> float:
    """Area under the precision-recall curve - the metric that matters when
    only ~11% of rows are positive and ranking the rare events is the job."""
    y = np.asarray(y).ravel()
    if y.sum() == 0:
        return float("nan")
    order = np.argsort(-p, kind="mergesort")
    hits = np.cumsum(y[order])
    precision = hits / np.arange(1, y.size + 1)
    return float((precision * y[order]).sum() / y.sum())


def brier(y: np.ndarray, p: np.ndarray) -> float:
    return float(np.mean((p - np.asarray(y).ravel()) ** 2))


def log_loss(y: np.ndarray, p: np.ndarray) -> float:
    q = np.clip(p, 1e-9, 1 - 1e-9)
    y = np.asarray(y).ravel()
    return float(-np.mean(y * np.log(q) + (1 - y) * np.log(1 - q)))


def calibration_table(y: np.ndarray, p: np.ndarray, bins: int = 10) -> list[dict[str, float]]:
    """Predicted vs observed frequency per decile of predicted risk.

    This is the table to read before trusting a risk *score*: AUC only says the
    ordering is right, calibration says a score of 70 really does correspond to
    roughly a 70% chance in the modelled world.
    """
    y = np.asarray(y).ravel()
    edges = np.linspace(0.0, 1.0, bins + 1)
    rows: list[dict[str, float]] = []
    for i in range(bins):
        low, high = edges[i], edges[i + 1]
        mask = (p >= low) & (p < high if i < bins - 1 else p <= high)
        if not mask.any():
            continue
        rows.append(
            {
                "bin_low": round(float(low), 3),
                "bin_high": round(float(high), 3),
                "count": int(mask.sum()),
                "mean_predicted": round(float(p[mask].mean()), 4),
                "observed_rate": round(float(y[mask].mean()), 4),
            }
        )
    return rows


def expected_calibration_error(rows: list[dict[str, float]], total: int) -> float:
    if total == 0:
        return float("nan")
    return float(
        sum(r["count"] * abs(r["mean_predicted"] - r["observed_rate"]) for r in rows) / total
    )


def evaluate(y: np.ndarray, p: np.ndarray) -> dict[str, Any]:
    table = calibration_table(y, p)
    return {
        "n": int(np.asarray(y).size),
        "positive_rate": round(float(np.mean(y)), 4),
        "roc_auc": round(roc_auc(y, p), 4),
        "pr_auc": round(average_precision(y, p), 4),
        "brier": round(brier(y, p), 4),
        "log_loss": round(log_loss(y, p), 4),
        "mean_predicted": round(float(p.mean()), 4),
        "ece": round(expected_calibration_error(table, int(np.asarray(y).size)), 4),
        "calibration": table,
    }


# -------------------------------------------------------------------- ensemble

def _proba(model: Any, X: np.ndarray) -> np.ndarray:
    """Positive-class probability, whichever backend produced the model."""
    return np.asarray(model.predict_proba(X), dtype=float)[:, 1]


def ensemble_proba(models: Sequence[Any], X: np.ndarray) -> np.ndarray:
    return np.mean([_proba(m, X) for m in models], axis=0)


def logit(p: np.ndarray) -> np.ndarray:
    q = np.clip(np.asarray(p, dtype=float), 1e-6, 1.0 - 1e-6)
    return np.log(q / (1.0 - q))


def ensemble_spread(models: Sequence[Any], X: np.ndarray) -> np.ndarray:
    """Disagreement between members, measured in log-odds.

    A wide spread means the members saw different bootstrap samples and reached
    different conclusions, which is exactly the signal `predict.py` turns into
    the reported confidence - rather than printing a number that looks like
    certainty but was never measured.

    Log-odds rather than probability, because probability spread shrinks
    automatically near 0 and 1: two members at 0.001 and 0.02 differ by a
    factor of twenty but only 0.019 in probability. Comparing that against a
    reference dominated by low-risk rows would report false certainty on
    exactly the rows an officer cares about.
    """
    if len(models) < 2:
        return np.zeros(X.shape[0], dtype=float)
    return np.std([logit(_proba(m, X)) for m in models], axis=0)


def _permutation_importance(
    models: Sequence[Any], X: np.ndarray, y: np.ndarray, *, seed: int = 17
) -> np.ndarray:
    """AUC lost when one column is shuffled.

    Needed because scikit-learn's HistGradientBoostingClassifier exposes no
    native importances, and the explainability panel must work on every backend.
    """
    rng = np.random.default_rng(seed)
    base = roc_auc(y, ensemble_proba(models, X))
    drops = np.zeros(X.shape[1], dtype=float)
    for i in range(X.shape[1]):
        shuffled = np.array(X, copy=True)
        shuffled[:, i] = shuffled[rng.permutation(X.shape[0]), i]
        drops[i] = max(0.0, base - roc_auc(y, ensemble_proba(models, shuffled)))
    return drops


def importance_table(
    models: Sequence[Any], X: np.ndarray, y: np.ndarray
) -> tuple[str, list[dict[str, Any]]]:
    """Per-feature importance shares, plus the method that produced them."""
    vectors = [
        np.asarray(m.feature_importances_, dtype=float)
        for m in models
        if hasattr(m, "feature_importances_")
    ]
    if vectors:
        totals = np.mean(vectors, axis=0)
        method = "split-gain"
    else:
        totals = _permutation_importance(models, X, y)
        method = "permutation-auc-drop"
    total = float(totals.sum())
    shares = totals / total if total > 0 else np.full(totals.size, 1.0 / totals.size)
    return method, [
        {
            "feature": FEATURE_ORDER[i],
            "group": FACTOR_GROUPS[FEATURE_ORDER[i]],
            "importance": round(float(shares[i]), 4),
        }
        for i in np.argsort(-shares)
    ]


def band_distribution(p: np.ndarray) -> dict[str, Any]:
    """Where predicted scores land across the five specified risk bands.

    Recorded so the demo cannot be accused of a model that never leaves one
    band: the card shows CRITICAL is reachable and how often it is reached.
    """
    scores = 100.0 * np.asarray(p, dtype=float)
    counts = {band: 0 for band in BAND_ORDER}
    for s in scores:
        counts[risk_level(float(s))] += 1
    total = max(1, int(scores.size))
    return {
        "counts": counts,
        "percent": {b: round(100.0 * c / total, 2) for b, c in counts.items()},
        "score_min": round(float(scores.min()), 2),
        "score_p50": round(float(np.percentile(scores, 50)), 2),
        "score_p95": round(float(np.percentile(scores, 95)), 2),
        "score_max": round(float(scores.max()), 2),
    }


# -------------------------------------------------------------------- training

PROVENANCE = {
    "data_mode": "DEMO",
    "feature_source": (
        "SIMULATED - hourly weather process in ml/hydrology.py over the "
        "approximate terrain table in ml/data/regions_seed.py"
    ),
    "label_source": (
        "SYNTHETIC - Bernoulli draws from the documented slope-stability model "
        "in ml/physics.py, plus 0.5% two-way observation noise"
    ),
    "real_world_validated": False,
    "notice": (
        "Every metric here measures how well the model recovers ml/physics.py "
        "from noisy samples of it. None of them is evidence of real-world "
        "landslide forecast skill, and no prediction from this model should be "
        "presented as an observed or verified forecast."
    ),
    "replace_with": (
        "GSI National Landslide Susceptibility Mapping inventory for labels, "
        "IMD gridded rainfall for weather, Bhuvan/SRTM/Cartosat DEM for terrain; "
        "swap ml/data/generate_dataset.py for a loader and nothing downstream changes"
    ),
}

LIMITATIONS = [
    "Trained on simulated data, so it reproduces a physical model rather than the observed landslide record.",
    "Hourly resolution and regional terrain averages - it cannot resolve an individual slope or a specific building.",
    "No earthquake, reservoir drawdown, blasting or excavation triggers are represented.",
    "Rainfall beyond the training range is clipped at the documented BOUNDS, so extreme what-if answers saturate rather than extrapolate.",
    "Decision support only: it does not replace inspection by a qualified geotechnical engineer.",
]


def _load_frame(
    path: Path, rows: int, seed: int, regenerate: bool, say: Callable[[str], None]
) -> pd.DataFrame:
    """Load the training CSV, generating it first if it is missing or too small."""
    frame: pd.DataFrame | None = None
    if path.exists() and not regenerate:
        frame = pd.read_csv(path)
        say(f"  data           {path} ({len(frame):,} rows)")
        if len(frame) < rows:
            say(f"  regenerating   have {len(frame):,} rows, need {rows:,}")
            frame = None
    if frame is None:
        from ml.data.generate_dataset import generate

        say(f"  generating     {rows:,} synthetic rows (seed {seed})")
        frame = generate(rows=rows, seed=seed)
        path.parent.mkdir(parents=True, exist_ok=True)
        frame.to_csv(path, index=False)
        say(f"  wrote          {path}")
    return frame.iloc[:rows].reset_index(drop=True) if len(frame) > rows else frame


def train(
    *,
    rows: int = 24_000,
    data_path: Path = DEFAULT_DATA,
    backend: str = "auto",
    members: int = 5,
    seed: int = 20260902,
    regenerate: bool = False,
    verbose: bool = True,
) -> tuple[dict[str, Any], dict[str, Any]]:
    """Fit the bagged ensemble; return the servable bundle and the model card."""

    def say(message: str) -> None:
        if verbose:
            print(message, flush=True)

    say("training landslide hazard model")
    frame = _load_frame(data_path, rows, seed, regenerate, say)
    X = frame_to_matrix(frame)
    y = labels(frame)
    groups = frame[GROUP_COLUMN].to_numpy()
    train_idx, val_idx, test_idx = group_split(groups)

    say(f"  rows           {X.shape[0]:,} | positives {int(y.sum()):,} ({100 * y.mean():.2f}%)")
    say(
        f"  grouped split  train {train_idx.size:,} / val {val_idx.size:,} / "
        f"test {test_idx.size:,} (no region in two splits)"
    )

    name, factory = resolve_backend(backend)
    say(f"  backend        {name}")

    # Bootstrap resample per member. This is real bagging, and for backends
    # without row subsampling of their own it is the only source of member
    # diversity - without it the "ensemble" would be five identical models and
    # the confidence derived from their spread would be meaningless.
    rng = np.random.default_rng(seed)
    fitted: list[Any] = []
    started = time.time()
    n_members = max(1, int(members))
    for member in range(n_members):
        picks = rng.integers(0, train_idx.size, size=train_idx.size)
        idx = train_idx[picks]
        model = factory(seed + 101 * member)
        model.fit(X[idx], y[idx])
        fitted.append(model)
        say(f"    member {member + 1}/{n_members} fitted ({time.time() - started:.1f}s elapsed)")
    elapsed = time.time() - started

    p_test = ensemble_proba(fitted, X[test_idx])
    spread = ensemble_spread(fitted, X[test_idx])

    metrics = {
        "train": evaluate(y[train_idx], ensemble_proba(fitted, X[train_idx])),
        "validation": evaluate(y[val_idx], ensemble_proba(fitted, X[val_idx])),
        "test": evaluate(y[test_idx], p_test),
    }
    imp_method, importance = importance_table(fitted, X[val_idx], y[val_idx])

    # The labels are Bernoulli draws, so even the generating probability cannot
    # score a perfect AUC against them. Measuring that limit is the only honest
    # way to say whether 0.83 is a good number or a poor one.
    ceiling: dict[str, Any] | None = None
    if "hazard_probability_true" in frame.columns:
        truth = frame["hazard_probability_true"].to_numpy(dtype=float)
        limit = roc_auc(y[test_idx], truth[test_idx])
        ceiling = {
            "note": (
                "ROC AUC of the generating probability itself against the sampled "
                "labels - the irreducible ceiling for any model of this data."
            ),
            "test_roc_auc": round(limit, 4),
            "model_fraction_of_ceiling": round(float(metrics["test"]["roc_auc"] / limit), 4),
            "correlation_with_true_probability": round(
                float(np.corrcoef(p_test, truth[test_idx])[0, 1]), 4
            ),
        }

    bundle: dict[str, Any] = {
        "format": "landslide-ensemble/1",
        "model_name": MODEL_NAME,
        "model_version": MODEL_VERSION,
        "feature_schema_version": FEATURE_SCHEMA_VERSION,
        "feature_order": list(FEATURE_ORDER),
        "backend": name,
        "member_format": "numpy-gbm-dict" if isinstance(fitted[0], NumpyGBM) else "estimator",
        "members": [m.to_dict() if isinstance(m, NumpyGBM) else m for m in fitted],
        "hyperparams": dict(HYPERPARAMS),
        "trained_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "training_seconds": round(elapsed, 2),
        "training_rows": int(X.shape[0]),
        "split_sizes": {
            "train": int(train_idx.size),
            "validation": int(val_idx.size),
            "test": int(test_idx.size),
        },
        "regions": {
            "total": int(np.unique(groups).size),
            "train": int(np.unique(groups[train_idx]).size),
            "validation": int(np.unique(groups[val_idx]).size),
            "test": int(np.unique(groups[test_idx]).size),
        },
        "metrics": metrics,
        "label_noise_ceiling": ceiling,
        "importance_method": imp_method,
        "feature_importance": importance,
        "band_distribution": band_distribution(p_test),
        "confidence_reference": {
            "note": (
                "Member disagreement in log-odds on held-out rows; predict.py scales "
                "the reported confidence against spread_p90."
            ),
            "spread_p50": round(float(np.percentile(spread, 50)), 4),
            "spread_p90": round(float(np.percentile(spread, 90)), 4),
            "spread_max": round(float(spread.max()), 4),
        },
        "training_summary": summarise(X[train_idx]),
        "data_provenance": dict(PROVENANCE),
        "intended_use": (
            "Screening and triage of landslide hazard across monitored regions, "
            "and interactive what-if exploration. Decision support only."
        ),
        "limitations": list(LIMITATIONS),
    }
    card = {key: value for key, value in bundle.items() if key != "members"}
    card["members"] = n_members
    return bundle, card


def main() -> int:
    parser = argparse.ArgumentParser(description="Train the landslide hazard model")
    parser.add_argument("--rows", type=int, default=24_000, help="training rows to use")
    parser.add_argument("--data", type=Path, default=DEFAULT_DATA)
    parser.add_argument("--out", type=Path, default=DEFAULT_MODEL)
    parser.add_argument("--card", type=Path, default=DEFAULT_CARD)
    parser.add_argument(
        "--backend",
        choices=["auto", "xgboost", "sklearn", "numpy"],
        default="auto",
        help="auto prefers xgboost, then scikit-learn, then the bundled NumPy GBM",
    )
    parser.add_argument("--members", type=int, default=5, help="bagged ensemble size")
    parser.add_argument("--seed", type=int, default=20260902)
    parser.add_argument("--regenerate", action="store_true", help="rebuild the CSV even if present")
    parser.add_argument("--quiet", action="store_true")
    args = parser.parse_args()

    bundle, card = train(
        rows=args.rows,
        data_path=args.data,
        backend=args.backend,
        members=args.members,
        seed=args.seed,
        regenerate=args.regenerate,
        verbose=not args.quiet,
    )

    args.out.parent.mkdir(parents=True, exist_ok=True)
    with args.out.open("wb") as handle:
        pickle.dump(bundle, handle, protocol=pickle.HIGHEST_PROTOCOL)
    args.card.write_text(json.dumps(card, indent=2), encoding="utf-8")

    if args.quiet:
        return 0

    test = card["metrics"]["test"]
    bands = card["band_distribution"]
    print(f"\nsaved model    {args.out}  ({args.out.stat().st_size / 1024:.0f} KB)")
    print(f"saved card     {args.card}")
    print("\nheld-out regions the model never saw")
    print(f"  ROC AUC      {test['roc_auc']:.4f}")
    print(f"  PR AUC       {test['pr_auc']:.4f}   (positive rate {test['positive_rate']:.4f})")
    print(f"  Brier        {test['brier']:.4f}")
    print(f"  calibration  ECE {test['ece']:.4f}")
    if card["label_noise_ceiling"]:
        ceiling = card["label_noise_ceiling"]
        print(
            f"  noise limit  {ceiling['test_roc_auc']:.4f} -> model reaches "
            f"{100 * ceiling['model_fraction_of_ceiling']:.1f}% of what is achievable"
        )
    print(f"\nscore range    {bands['score_min']:.1f} - {bands['score_max']:.1f}")
    print("  " + "  ".join(f"{b} {bands['percent'][b]:.1f}%" for b in BAND_ORDER))
    print(f"\ntop drivers ({card['importance_method']})")
    for row in card["feature_importance"][:6]:
        print(f"  {row['feature']:<28} {100 * row['importance']:5.1f}%   {row['group']}")
    print(
        "\nSYNTHETIC TRAINING DATA. These metrics describe how well the model "
        "recovers\nml/physics.py - they are not real-world landslide forecast skill."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())






